### ISSUE TITLE
Images with wrong ratio generated

### ISSUE THREAD

**Issue by georgringer** [smichaelsen/melon-images#75]
currently using `dev-task/typo3v12-compat` and TYPO3 v12 and got an issue that the ratio is not really respected.

config

```yaml
  tt_address:
    _all:
      image:
        variants:
          default:
            sizes:
              desktop:
                breakpoints: desktop
                width: 340
                ratio: 1/1
              tablet:
                breakpoints: tablet
                width: 300
                ratio: 1/1
              phone:
                breakpoints: phone
                width: 500
                ratio: 1/1
```

this occurs if the image is **not** changed in the backend but just assigned as media, however (!) if I use the regular `f:image` viewhelper, everything looks ok!
```html
<f:for each="{address.image}" as="image">
            <melon:responsivePicture fileReference="{image}" variant="default" title="{address.fullName}" additionalImageAttributes="{loading: 'lazy', class: 'img-fluid w-100', width: '300'}" />
          <f:image image="{image}" cropVariant="tt_address___all__image__default__1/1" maxWidth="200" />
</f:for>
```

the images generated by melonimages are not 1:1 but 259x289 (when a 900x1000 image provided) but the regular ones are fine..
